web/router.ex
defmodule Pullhub.Router do
  use Pullhub.Web, :router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug Pullhub.Plugs.Authenticate
    plug Pullhub.Plugs.GenerateUserToken
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Pullhub do
    pipe_through [:browser, :auth] # Use the default browser stack
    get "/", PullRequestController, :index
    delete "/logout", AuthController, :delete

    resources "/repositories", RepositoryController
    resources "/pull_requests", PullRequestController
  end

  scope "/", Pullhub do
    pipe_through :browser
    get "/auth", AuthController, :index
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback
    post "/auth/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Pullhub do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Pullhub.LayoutView do
  use Pullhub.Web, :view

  def title(conn) do
    [conn.assigns[:page_title], "Pullhub"]
    |> Enum.join(" | ")
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= tag :meta, name: "user_token", content: assigns[:user_token] %>
    <%= tag :meta, name: "user_id", content: assigns[:current_user].id %>

    <title><%= title(@conn) %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

    <div class="container py-5">
      <div class="columns">
        <div class="one-fifth column pb-3">
          <h1>Pullhub</h1>
        </div>
      </div>
      <div class="columns">
        <div class="one-fifth column">
          <%= if @current_user do %>
          <nav class="menu">
            <%=
            active_link(@conn, "Pull requests", to: pull_request_path(@conn, :index), class: "menu-item")
            %>

            <%=
            active_link(@conn, "Repositories", to: repository_path(@conn, :index), class: "menu-item")
            %>
          </nav>

          <nav class="menu">
            <li>
              <%= link "Log out", to: auth_path(@conn, :delete), method: :delete, class: "menu-item" %>
            </li>
          </nav>
          <% end %>
        </div>
        <div class="four-fifths column">
          <p class="flash flash-info" role="flash"><%= get_flash(@conn, :info) %></p>
          <p class="flash flash-error" role="flash"><%= get_flash(@conn, :error) %></p>

          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/auth_layout.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pullhub!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>