web/router.ex
defmodule Pullhub.Router do
  use Pullhub.Web, :router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth do
    plug Pullhub.Plugs.Authenticate
    plug Pullhub.Plugs.GenerateUserToken
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Pullhub do
    pipe_through [:browser, :auth] # Use the default browser stack
    get "/", PullRequestController, :index
    delete "/logout", AuthController, :delete

    resources "/repositories", RepositoryController
    resources "/pull_requests", PullRequestController
  end

  scope "/", Pullhub do
    pipe_through :browser
    get "/auth", AuthController, :index
    get "/auth/:provider", AuthController, :request
    get "/auth/:provider/callback", AuthController, :callback
    post "/auth/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Pullhub do
  #   pipe_through :api
  # end
end

lib/pullhub/pull_requests/pull_request.ex
defmodule Pullhub.PullRequest do
  use Pullhub.Web, :model

  schema "pull_requests" do
    field :title, :string
    field :body, :string
    field :remote_id, :integer
    field :author_login, :string
    field :assignees_logins, {:array, :string}
    field :assignees_avatars, {:array, :string}
    field :state, :string
    field :issue_url, :string
    field :url, :string
    belongs_to :repository, Pullhub.Repository
    belongs_to :author, Pullhub.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body, :assignees_logins, :assignees_avatars, :author_login, :remote_id, :state, :issue_url, :url, :repository_id])
    |> validate_required([:title, :body, :remote_id, :state, :issue_url, :url])
  end
end

lib/pullhub/pull_requests/pull_requests.ex
defmodule Pullhub.PullRequests do

  import Pullhub.PullRequests.Queries

  alias Pullhub.Repository
  alias Pullhub.PullRequest
  alias Pullhub.Repo

  def insert_pull_requests(pull_requests, %Repository{id: repo_id}) do
    pull_requests
    |> Enum.map(&add_repository_id_to_pull_request(&1, repo_id))
    |> insert_pull_requests
  end

  defp insert_pull_requests(pulls) do
    pulls
    |> Enum.map(fn(pull) -> Repo.insert(pull) end)
  end

  def pull_requests(%Repository{id: repo_id} = repo) do
    repo
    |> find_by_repository
    |> Repo.all
  end

  def remove_pull_requests(%Repository{id: repo_id} = repo) do
    repo
    |> find_by_repository
    |> Repo.delete_all
  end

  defp add_repository_id_to_pull_request(%PullRequest{} = pull, repo_id) do
    %{ pull | repository_id: repo_id }
  end
end

lib/pullhub/pull_requests/queries.ex
defmodule Pullhub.PullRequests.Queries do

  import Ecto.Query

  alias Pullhub.Repository
  alias Pullhub.PullRequest

  def find_by_repository(%Repository{id: repo_id}) do
    PullRequest |> where([p], p.repository_id == ^repo_id)
  end

  def open_pull_requests, do: PullRequest |> where(state: "open")
end

lib/pullhub/pull_requests/sync.ex
defmodule Pullhub.PullRequests.Sync do
  alias Pullhub.GithubApi
  alias Pullhub.Repo
  alias Pullhub.Repositories
  alias Pullhub.PullRequests
  alias Pullhub.User

  def sync(%User{} = user) do
    user
    |> enabled_user_repositories
    |> download_pull_requests(user)
  end

  defp download_pull_requests(repositories, %User{} = user) do
    Enum.map(repositories, fn(repo) ->
      Pullhub.GithubApi.pull_requests(repo, user)
      |> update_stored_data(repo)

    end)
    repositories
  end

  defp enabled_user_repositories(%User{} = user) do
    user.id |> Repositories.user_repos
  end

  defp update_stored_data({:error, message}, _) do
  end

  defp update_stored_data(pull_requests, repo) do
    PullRequests.remove_pull_requests(repo)
    PullRequests.insert_pull_requests(pull_requests, repo)
  end
end

web/models/pull_request.ex
defmodule Pullhub.PullRequest do
  use Pullhub.Web, :model

  schema "pull_requests" do
    field :title, :string
    field :body, :string
    field :remote_id, :integer
    field :author_login, :string
    field :assignees_logins, {:array, :string}
    field :assignees_avatars, {:array, :string}
    field :state, :string
    field :issue_url, :string
    field :url, :string
    belongs_to :repository, Pullhub.Repository
    belongs_to :author, Pullhub.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body, :assignees_logins, :assignees_avatars, :author_login, :remote_id, :state, :issue_url, :url, :repository_id])
    |> validate_required([:title, :body, :remote_id, :state, :issue_url, :url])
  end

  def open_pull_requests do
    from(p in Pullhub.PullRequest, where: p.state == "open")
  end
end

web/controllers/pull_request_controller.ex
defmodule Pullhub.PullRequestController do
  use Pullhub.Web, :controller

  alias Pullhub.Repositories

  def index(conn, _params) do
    conn
    |> assign(:page_title, "Pull requests")
    |> render("index.html", repositories: user_repos(conn))
  end

  def user_id(conn) do
    conn.assigns[:current_user].id
  end

  def user_repos(conn) do
    user_id(conn)
    |> Repositories.user_repos
  end
end

web/views/pull_request_view.ex
defmodule Pullhub.PullRequestView do
  use Pullhub.Web, :view

  def mark_if_assigned(pull_request, user) do
    users = Enum.filter(pull_request.assignees_logins,
        fn(assignee) -> assignee == user.uid end)

    if Enum.count(users) > 0 do
      "highlight"
    end
  end

  def hide_class_if_empty(repository) do
    if Enum.count(repository.pull_requests) == 0 do
      "hidden"
    end
  end
end

web/templates/pull_request/index.html.eex
<p id="pullrequest-fetch-info" class="flash flash-info">Fetching latest data from Github</p>

<%= if !List.first(@repositories) do %>
  <div class="blankslate">
    <h3>You haven't enabled any repositories yet.</h3>
    <p>
      To make this tool useful go to the
      <%= link "repositories management page", to: repository_path(@conn, :index) %>
      to enable som repositories
    </p>
  </div>
<% end %>

<%= if List.first(@repositories) do %>
  <%= for repository <- @repositories do %>
    <div class="pull-request-repository <%= hide_class_if_empty(repository) %>">
      <div class="pull-request-repository-header">
        <div class="pull-request-repository-header-inner">
          <h4>
            <%= repository.name %>
            <span class="pull-request-repository-header-owner">
                <%= repository.owner %>
            </span>
          </h4>
        </div>
      </div>
      <div class="pull-requests-container">
        <ul class="" id="repository-pull-requests-<%= repository.id %>">
          <%= for pull_request <- repository.pull_requests do %>
            <%= render Pullhub.PullRequestView, "pull_request.html", conn: @conn, repository: repository, pull_request: pull_request %>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

web/templates/pull_request/pull_request.html.eex
<li class="list-item">
  <div class="list-item-inner">
    <div class="list-item-checkbox">
      <span class="tooltipped tooltipped-n" aria-label="Open pull request">
        <%= render Pullhub.PullRequestView, "pull_request_icon.html" %>
      </span>
    </div>

    <div class="list-item-main">
      <%= link @pull_request.title, to: @pull_request.url, class: "list-item-main-link" %>

      <div class="list-item-main-description">
        by <%= @pull_request.author_login %>
      </div>
    </div>

    <div class="list-item-avatars">
      <div class="list-item-avatars-inner">
        <div class="avatar-stack" aria-label="Assigned to ">
          <%= if @pull_request.assignees_avatars do %>
            <%= for avatar <- @pull_request.assignees_avatars do %>
              <img class="avatar avatar-small" src="<%= avatar %>" width="32" height="32">
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

web/templates/pull_request/pull_request_icon.html.eex
<svg aria-hidden="true" class="octicon octicon-git-pull-request open" height="16" version="1.1" viewBox="0 0 12 16" width="12"><path fill-rule="evenodd" d="M11 11.28V5c-.03-.78-.34-1.47-.94-2.06C9.46 2.35 8.78 2.03 8 2H7V0L4 3l3 3V4h1c.27.02.48.11.69.31.21.2.3.42.31.69v6.28A1.993 1.993 0 0 0 10 15a1.993 1.993 0 0 0 1-3.72zm-1 2.92c-.66 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2zM4 3c0-1.11-.89-2-2-2a1.993 1.993 0 0 0-1 3.72v6.56A1.993 1.993 0 0 0 2 15a1.993 1.993 0 0 0 1-3.72V4.72c.59-.34 1-.98 1-1.72zm-.8 10c0 .66-.55 1.2-1.2 1.2-.65 0-1.2-.55-1.2-1.2 0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2zM2 4.2C1.34 4.2.8 3.65.8 3c0-.65.55-1.2 1.2-1.2.65 0 1.2.55 1.2 1.2 0 .65-.55 1.2-1.2 1.2z"></path></svg>